field: 8823155c-e84a-4a38-af30-2cb88b705e7b
fieldLayouts:
  569a9c10-0657-4dbf-87c9-005afb784b54:
    tabs:
      -
        elements:
          -
            fieldUid: 39b59166-9d91-4d17-baf9-229aca6174c2
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4ed4bf91-bcf9-45a9-84f7-d5d768103a09
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a418bde2-f4cc-4ed2-a358-44362a0cb3a9
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  39b59166-9d91-4d17-baf9-229aca6174c2:
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: ''
    name: Quote
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  4ed4bf91-bcf9-45a9-84f7-d5d768103a09:
    contentColumnType: text
    fieldGroup: null
    handle: cite
    instructions: ''
    name: Cite
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a418bde2-f4cc-4ed2-a358-44362a0cb3a9:
    contentColumnType: string
    fieldGroup: null
    handle: photo
    instructions: ''
    name: Photo
    searchable: true
    settings:
      allowSelfRelations: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:0193dc64-5499-4e28-95dd-f8f603154851'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:0193dc64-5499-4e28-95dd-f8f603154851'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:0193dc64-5499-4e28-95dd-f8f603154851'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: testimonial
name: Testimonial
sortOrder: 1
