field: 82ac4aa6-3b63-4cb9-a1f6-6cb6a5210a2e
fieldLayouts:
  4ade673e-0245-430b-b932-c8ea86e36773:
    tabs:
      -
        elements:
          -
            fieldUid: e03a8ea1-0b9b-4e8c-bbf5-f7197caad45c
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cc6a4697-6d1c-4342-b9de-bce13295a885
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  cc6a4697-6d1c-4342-b9de-bce13295a885:
    contentColumnType: string
    fieldGroup: null
    handle: position
    instructions: ''
    name: Position
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Center
            -
              - value
              - center
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  e03a8ea1-0b9b-4e8c-bbf5-f7197caad45c:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: text
name: Text
sortOrder: 3
