fieldLayouts:
  b89ba12c-3f9b-4e8d-a190-073678e01175:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: aef80333-1412-4130-bb84-ac3bdbbcbbe2
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0cbb9736-a84b-4e83-803c-5077f56394a9
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4ca9d3b8-ff02-403a-9010-45763fcdea9f
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: link
hasTitleField: true
name: Link
section: f5969f9a-8d3f-487e-9695-cc4e5fbe5efd
sortOrder: 0
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
