fieldLayouts:
  e4360fb7-190d-42c5-bde0-e01c03bd127c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: aef80333-1412-4130-bb84-ac3bdbbcbbe2
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: siteAssets
hasUrls: true
name: 'Site Assets'
settings:
  path: '@assetBasePath/site'
sortOrder: 1
type: craft\volumes\Local
url: '@assetBaseUrl/site'
