fieldLayouts:
  2d9fb3d5-a903-4ef4-81f3-9eb72e49e728:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: userPhotos
hasUrls: false
name: 'User Photos'
settings:
  path: '@storage/userphotos'
sortOrder: 4
type: craft\volumes\Local
url: null
