contentColumnType: string
fieldGroup: 0d0b7e16-8d7c-4d6f-9059-d11c473058f4
handle: articleBody
instructions: ''
name: 'Article Body'
searchable: true
settings:
  contentTable: '{{%matrixcontent_articlebody}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
