contentColumnType: text
fieldGroup: 0d0b7e16-8d7c-4d6f-9059-d11c473058f4
handle: indexHeading
instructions: 'Page heading for services structure index page.'
name: 'Index Heading'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  cleanupHtml: true
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: ''
  removeInlineStyles: ''
  removeNbsp: ''
  showHtmlButtonForNonAdmins: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
