contentColumnType: string(1020)
fieldGroup: 0d0b7e16-8d7c-4d6f-9059-d11c473058f4
handle: linkUrl
instructions: ''
name: 'Link URL'
searchable: true
settings:
  byteLimit: null
  charLimit: 255
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'e.g. http://example.com'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
