dateModified: 1623776373
email:
  fromEmail: admin@happylager.dev
  fromName: Happylager
  template: null
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0cbb9736-a84b-4e83-803c-5077f56394a9: 'Featured Image' # Featured Image
    0d0b7e16-8d7c-4d6f-9059-d11c473058f4: General # General
    0f3ede99-8b78-4042-85c9-422f57f5b01b: Gallery # Gallery
    0f910d7c-0ba2-476a-a7c9-fa489255e601: Thumb # Thumb
    1a1f289d-3e32-4409-bfb2-03ec7e7d1b81: About # About
    1d5e20da-bc96-4a33-b045-8d1fa5870e74: Heading # Heading
    1f0ea10d-2be0-4638-88da-105d232f4787: 'User Photos' # User Photos
    1f72a359-0ce9-4415-82dc-88dc833073c3: Homepage # Homepage
    1ff1d4d0-499c-41b9-b071-77031c901052: 'Work Index' # Work Index
    3fc34ff2-8da7-4a35-8147-f0a2e01392b9: 'Service Icons' # Service Icons
    4ca9d3b8-ff02-403a-9010-45763fcdea9f: 'Link URL' # Link URL
    4ed4bf91-bcf9-45a9-84f7-d5d768103a09: Cite # Cite
    5fa323b7-9755-4174-bed2-0f2b11c05701: 'Services Index' # Services Index
    6ef72b30-6af9-4545-81e9-b2c900cd08d4: About # About
    06f4e499-3cdc-4d64-aec2-9a7d3a143c75: 'Happy Lager (en)' # Happy Lager (en)
    7ca32393-f78c-4de0-9f8f-52b64e09584f: Caption # Caption
    7d6a9bef-727c-4a0c-9791-4f423956de69: 'Company Logos' # Company Logos
    7f0d6d70-ed28-45f1-88c0-4463e96f110f: 'Services Index' # Services Index
    8b4aae04-76ef-48c2-a294-e81064a470ed: Services # Services
    8cd6b011-5271-484d-85d9-6a6b731137e9: 'Section Heading' # Section Heading
    8dbeba09-2202-4eb4-8f3c-b15633a4830d: 'Footer Content' # Footer Content
    08f8ec90-f7ad-4d40-9880-3c96304f1e4e: Body # Body
    9bb293f8-c659-4035-b5d3-e30dbf8d1c5b: Heading # Heading
    9bf9e642-2881-44b4-99ff-2cbed3ccc2d7: 'Service Body' # Service Body
    9ce53ce9-939b-4760-97f4-545ef2c388eb: Image # Image
    36f99c8f-0ba4-4e4c-af7d-a07dee715ac1: Medium # Medium
    39b59166-9d91-4d17-baf9-229aca6174c2: Quote # Quote
    41e6fac7-12d7-45c9-ac83-0aa59793d872: Attribution # Attribution
    45d3a977-dc34-4bff-a39f-425e100a5e6f: Locations # Locations
    67ff16f0-04e2-492b-b999-a7d364331d80: 'Index Heading' # Index Heading
    070be8db-f9b0-4605-98ae-e9b54b1af3f6: Text # Text
    82ac4aa6-3b63-4cb9-a1f6-6cb6a5210a2e: 'Article Body' # Article Body
    97ff3c80-2398-4ca5-9d03-c3b8727c6eb2: Quote # Quote
    0193dc64-5499-4e28-95dd-f8f603154851: 'Site Assets' # Site Assets
    261c3cde-2d6c-4b23-b6cd-6def95992cf8: 'Work Index' # Work Index
    268c3c49-6715-4b6a-a1b9-f27313adabd1: 'Happy Lager (en)' # Happy Lager (en)
    0305c984-3934-4c7a-9de9-b0162c5b0112: 'Featured Thumb' # Featured Thumb
    422c7da9-d3e4-4d0a-8225-bbbc8264f029: Address # Address
    631f668a-3658-48a4-89fd-8da5af0a60cc: Heading # Heading
    674e53a6-d62c-4322-ae09-349765f1ef17: Subheading # Subheading
    950b3c0e-9780-4487-a881-23d96d6075d5: 'Client Logos' # Client Logos
    964a1aba-15ac-413f-86c1-03fbf37f30c7: Image # Image
    992fb441-6b13-4051-aacd-e39943354507: 'Public Schema' # Public Schema
    3285a611-4363-43f2-82b5-97e2d253cab3: Heading # Heading
    0275193a-3c51-46a3-afd0-49e55a93bfd3: Value # Value
    726664b6-90aa-4fa9-9d03-23be4ba628bc: Small # Small
    735318f3-e53c-4ce1-8dad-4c7a5c7c5bee: Homepage # Homepage
    0815347a-8e73-45fd-93c9-2244ac562559: 'Contact Info' # Contact Info
    01416786-fb23-483e-9b86-d70279bf18a9: Work # Work
    5095500e-4962-429c-9b9c-7a4d0d4f930c: 'Copyright Notice' # Copyright Notice
    8823155c-e84a-4a38-af30-2cb88b705e7b: Testimonials # Testimonials
    9123201b-837c-4269-9d7c-d5e11bba1e2b: Image # Image
    35200549-df46-4092-994a-a8015c5810ba: Quote # Quote
    a5b4b046-1178-45f9-b4cf-3e3bef86e067: Position # Position
    a8a6d843-bec1-4882-98ec-30cb74f5b16f: 'Pull Quote' # Pull Quote
    a88d73a8-c75f-4c72-aa70-a39dfbbff0fe: Position # Position
    a171d498-9024-4855-9a6c-b3b96765ab7c: 'Featured?' # Featured?
    a418bde2-f4cc-4ed2-a358-44362a0cb3a9: Photo # Photo
    a988d6b4-6983-48e6-b08e-8fd72e31e483: 'Services Performed' # Services Performed
    a2129d62-1d81-4c2f-a92d-81c03ed120dc: 'Hero Image' # Hero Image
    aa39e3a4-2d2c-4ed2-a9b5-74122ece5947: 'Service Point' # Service Point
    aad31ad0-0405-41b5-aff0-4ec567b557a0: Label # Label
    ae84d93c-8a94-4605-bf08-11ada918f964: Locations # Locations
    aef80333-1412-4130-bb84-ac3bdbbcbbe2: 'Short Description' # Short Description
    b01498fe-6db2-4b1d-84d2-8cd0cb62f449: 'Contact Methods' # Contact Methods
    b3a9eef3-9444-4995-84e2-6dc6b60aebd2: Work # Work
    b3d2e2ed-d430-48c9-b89f-a38a7f8ea8b3: Testimonial # Testimonial
    b31c607b-b75a-4a78-b14b-d94bf8faa0c3: Link # Link
    b75266c9-d8d2-42ae-9024-0fecb8bdc994: Email # Email
    ba8a1276-24c8-43eb-94d4-b2a19c0c1bf7: Images # Images
    c09d31ed-3004-484c-89ef-e9d262f31f00: Services # Services
    c9ccf068-4ace-4b21-9356-68f3faa96cf3: Text # Text
    cc6a4697-6d1c-4342-b9de-bce13295a885: Position # Position
    cdcff4b0-ece0-4d03-8d9f-6ab5939c1bea: 'Background Color' # Background Color
    d58a1faa-0bf6-46b2-b880-b0c14bebca75: Homepage # Homepage
    d96355a7-1353-4097-bf08-3bd5c44821f8: 'Service Icon' # Service Icon
    daa4f1b9-ebde-4b0e-9cf3-027bf3b8b890: 'Pull Quote' # Pull Quote
    e03a8ea1-0b9b-4e8c-bbf5-f7197caad45c: Text # Text
    e1c6c95e-a19b-4cd8-9a83-935e91f862c0: 'New Section' # New Section
    eba60966-6218-4985-b901-fff1e5f97a49: Article # Article
    ecd6fdce-8d11-4aa6-a167-e731757515c6: 'Contact Method' # Contact Method
    f00e1793-0757-46e5-99e9-016b21359ac7: Work # Work
    f6b0cb16-5df8-4b57-9856-c9c2d6b9699e: Services # Services
    f87a6243-5b7f-4456-9106-ccfb6e03b754: Position # Position
    f5969f9a-8d3f-487e-9695-cc4e5fbe5efd: News # News
    f7189ca2-4b93-4661-830a-a71aff8aa3cd: Footer # Footer
    fcf41a5f-68b5-42dd-8ca1-cc457eb749f0: 'Contact Us Label' # Contact Us Label
plugins:
  redactor:
    enabled: '1'
    licenseKey: null
    schemaVersion: 2.3.0
    settings: null
system:
  edition: pro
  live: true
  name: 'Happy Lager'
  schemaVersion: 3.7.7
  timeZone: UTC
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: 1f0ea10d-2be0-4638-88da-105d232f4787 # User Photos
  requireEmailVerification: true
