dateModified: 1600294664
email:
  fromEmail: admin@happylager.dev
  fromName: Happylager
  template: null
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  redactor:
    enabled: '1'
    licenseKey: null
    schemaVersion: 2.3.0
    settings: null
system:
  edition: pro
  live: true
  name: 'Happy Lager'
  schemaVersion: 3.5.13
  timeZone: UTC
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: 1f0ea10d-2be0-4638-88da-105d232f4787
  requireEmailVerification: true
