enableVersioning: true
handle: news
name: News
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  06f4e499-3cdc-4d64-aec2-9a7d3a143c75:
    enabledByDefault: true
    hasUrls: true
    template: news/_entry
    uriFormat: 'news/{slug}'
type: channel
