enableVersioning: true
handle: services
name: Services
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  06f4e499-3cdc-4d64-aec2-9a7d3a143c75:
    enabledByDefault: true
    hasUrls: true
    template: services/_entry
    uriFormat: 'services/{slug}'
structure:
  maxLevels: 1
  uid: aa3fe533-8552-43f9-a172-69982d59561d
type: structure
